import path from 'node:path';
import { mkdir, writeFile } from 'node:fs/promises';
import { spawn } from 'node:child_process';
import { validateScreenDsl, normalizeScreenDsl } from '@dsl/screen-dsl';
import { DesignSystemRegistry, demoComponents, validateSemantics } from '@dsl/design-system-registry';
import { MockScreenDslProvider } from '@dsl/prompt-planner';
import { toAngularPageGenerationModel } from '@dsl/angular-generation-model';
import { writeAngularProject } from '@dsl/angular-generator';
import { validateGeneratedProject } from '@dsl/generation-validator';
import { nowIso, GenerationLog } from '@dsl/shared';
const prompt='Crie uma página de listagem de contratos. A página deve possuir título “Contratos”, botão “Novo contrato”, campo de pesquisa por número ou fornecedor, filtro por status, tabela paginada, indicador de carregamento, estado vazio e estado de erro. A tabela deve mostrar número, fornecedor, status e valor. Use dados mockados e somente componentes do Design System.';
export async function runContractsGeneration(){ const logs:GenerationLog[]=[]; const log=(stage:GenerationLog['stage'],message:string)=>logs.push({stage,level:'info',message,createdAt:nowIso()}); const root=process.cwd(); const out=path.join(root,'generated/contracts-project'); const provider=new MockScreenDslProvider(); log('GENERATING_DSL','Gerando DSL mockada'); const generated=await provider.generate({prompt,pageType:'list-page',route:'/contratos',components:demoComponents}); log('VALIDATING_SCHEMA','Validando JSON Schema'); const structural=validateScreenDsl(generated.dsl); if(!structural.valid) throw new Error(JSON.stringify(structural.issues)); log('VALIDATING_SEMANTICS','Validando semântica'); const semantic=validateSemantics(structural.data,new DesignSystemRegistry()); if(semantic.some(i=>i.severity==='error')) throw new Error(JSON.stringify(semantic)); log('NORMALIZING_DSL','Normalizando DSL'); const normalized=normalizeScreenDsl(structural.data); log('CREATING_GENERATION_MODEL','Criando modelo Angular'); const model=toAngularPageGenerationModel(normalized); log('GENERATING_ANGULAR','Gerando projeto Angular'); const files=await writeAngularProject(path.join(root,'packages/project-templates/angular-template'),out,model); log('BUILDING','Executando validação estática do build'); const issues=await validateGeneratedProject(out); if(issues.length) throw new Error(JSON.stringify(issues)); log('PACKAGING','Empacotando ZIP'); await mkdir(path.join(root,'storage'),{recursive:true}); const zipPath=path.join(root,'storage/contracts-project.zip'); await zip(out,zipPath); await writeFile(path.join(root,'storage/contracts-generation.json'),JSON.stringify({logs,dsl:generated.dsl,normalizedDsl:normalized,files,zipPath},null,2)); log('COMPLETED','Geração concluída'); return {logs,files,zipPath,out}; }
async function zip(src:string,dest:string){ await new Promise<void>((resolve,reject)=>{ const child=spawn('zip',['-qr',dest,'.'],{cwd:src}); child.on('close',code=>code===0?resolve():reject(new Error(`zip failed ${code}`))); child.on('error',reject);});}
if(import.meta.url===`file://${process.argv[1]}`){ const result=await runContractsGeneration(); console.log(JSON.stringify({zipPath:result.zipPath,files:result.files.map(f=>f.path)},null,2)); }
