import { ScreenDsl } from '@dsl/screen-dsl';
import { DesignSystemComponentDefinition } from '@dsl/design-system-registry';
import { ValidationIssue } from '@dsl/shared';
export interface GenerateDslInput { prompt:string; pageType:'list-page'|'form-page'|'detail-page'; route:string; components:DesignSystemComponentDefinition[]; }
export interface RepairDslInput { dsl:ScreenDsl; issues:ValidationIssue[]; components:DesignSystemComponentDefinition[]; }
export interface ScreenDslResult { dsl:ScreenDsl; raw:string; provider:'mock'|'openai'|'anthropic'; }
export interface ScreenDslProvider { generate(input:GenerateDslInput):Promise<ScreenDslResult>; repair(input:RepairDslInput):Promise<ScreenDslResult>; }
export class MockScreenDslProvider implements ScreenDslProvider { async generate(input:GenerateDslInput):Promise<ScreenDslResult>{ const dsl=contractsDsl(input.route); return {dsl,raw:JSON.stringify(dsl),provider:'mock'};} async repair(input:RepairDslInput):Promise<ScreenDslResult>{return {dsl:input.dsl,raw:JSON.stringify(input.dsl),provider:'mock'};} }
export class OpenAiScreenDslProvider implements ScreenDslProvider { async generate():Promise<ScreenDslResult>{ throw new Error('OpenAI provider preparado, configure OPENAI_API_KEY para implementação real.');} async repair():Promise<ScreenDslResult>{ throw new Error('OpenAI repair provider não configurado.');}}
export class AnthropicScreenDslProvider implements ScreenDslProvider { async generate():Promise<ScreenDslResult>{ throw new Error('Anthropic provider preparado, configure ANTHROPIC_API_KEY para implementação real.');} async repair():Promise<ScreenDslResult>{ throw new Error('Anthropic repair provider não configurado.');}}
export function buildModelInstruction(components:DesignSystemComponentDefinition[]):string{return `Responda somente JSON ScreenDsl 1.0; não gere código; use apenas componentes: ${components.map(c=>c.id).join(', ')}; inclua estados obrigatórios.`;}
function contractsDsl(route:string):ScreenDsl{return {dslVersion:'1.0',page:{name:'contract-list',route,title:'Contratos',type:'list-page',layout:'standard'},state:[{name:'loading',type:'boolean',defaultValue:false},{name:'empty',type:'boolean',defaultValue:false},{name:'error',type:'boolean',defaultValue:false},{name:'loaded',type:'boolean',defaultValue:true},{name:'search',type:'string',defaultValue:''},{name:'status',type:'string',defaultValue:''},{name:'page',type:'number',defaultValue:1}],dataSources:[{id:'contracts',type:'mock',model:'Contract',data:[{number:'CTR-001',supplier:'Acme Ltda',status:'Ativo',value:'R$ 12.000,00'},{number:'CTR-002',supplier:'Globex',status:'Pendente',value:'R$ 8.500,00'}]}],regions:[{id:'header',type:'header',components:[{id:'page-header',componentId:'ds-page-header',props:{title:'Contratos',description:'Gestão de contratos'},children:[{id:'new-contract',componentId:'ds-button',props:{label:'Novo contrato',variant:'primary',size:'md'},events:{clicked:{type:'navigate',target:'/contratos/novo'}}}]}]},{id:'search',type:'search',components:[{id:'contract-search',componentId:'ds-search-input',props:{label:'Pesquisa',placeholder:'Número ou fornecedor'},events:{search:{type:'set-state',state:'search',value:''}}}]},{id:'filters',type:'filters',components:[{id:'status-filter',componentId:'ds-select',props:{label:'Status',value:'',options:[{label:'Todos',value:''},{label:'Ativo',value:'Ativo'},{label:'Pendente',value:'Pendente'}]},events:{valueChange:{type:'set-state',state:'status',value:''}}}]},{id:'content',type:'content',components:[{id:'contracts-table',componentId:'ds-table',props:{columns:[{key:'number',label:'Número'},{key:'supplier',label:'Fornecedor'},{key:'status',label:'Status'},{key:'value',label:'Valor'}],rows:[]},dataSource:'contracts'}]},{id:'pagination',type:'pagination',components:[{id:'contracts-pagination',componentId:'ds-pagination',props:{page:1,pageSize:10,total:2},events:{pageChange:{type:'set-state',state:'page',value:1}}}]},{id:'loading',type:'loading',components:[{id:'loading-state',componentId:'ds-loading',props:{label:'Carregando contratos'},condition:'loading'}]},{id:'empty',type:'empty',components:[{id:'empty-state',componentId:'ds-empty-state',props:{title:'Nenhum contrato encontrado',description:'Ajuste os filtros ou cadastre um contrato.'},condition:'empty'}]},{id:'error',type:'error',components:[{id:'error-state',componentId:'ds-alert',props:{title:'Erro ao carregar',message:'Não foi possível carregar os contratos.',tone:'danger'},condition:'error'}]}]};}
