import Ajv2020 from 'ajv/dist/2020.js';
import addFormats from 'ajv-formats';
import { JsonValue, ValidationIssue, slugify } from '@dsl/shared';
export type PageType='list-page'|'form-page'|'detail-page'; export type RegionType='header'|'actions'|'search'|'filters'|'content'|'pagination'|'loading'|'empty'|'error'|'sections'|'cards';
export interface PageDefinition { name:string; route:string; title:string; type:PageType; layout:'standard'; }
export interface StateDefinition { name:string; type:'string'|'number'|'boolean'|'object'|'array'; defaultValue:JsonValue; }
export interface DataSourceDefinition { id:string; type:'mock'; model:string; data:JsonValue[]; }
export type Action={type:'navigate';target:string}|{type:'set-state';state:string;value:JsonValue}|{type:'reset-form';form:string}|{type:'submit-mock';form:string}|{type:'open-dialog';dialog:string};
export interface ComponentNode { id:string; componentId:string; props:Record<string,JsonValue>; bindings?:Record<string,string>; events?:Record<string,Action>; children?:ComponentNode[]; dataSource?:string; condition?:'loading'|'empty'|'error'|'loaded'; }
export interface RegionDefinition { id:string; type:RegionType; components:ComponentNode[]; }
export interface ScreenDsl { dslVersion:'1.0'; page:PageDefinition; state:StateDefinition[]; dataSources:DataSourceDefinition[]; regions:RegionDefinition[]; }
export const screenDslSchema={ $schema:'https://json-schema.org/draft/2020-12/schema', type:'object', additionalProperties:false, required:['dslVersion','page','state','dataSources','regions'], properties:{ dslVersion:{const:'1.0'}, page:{$ref:'#/$defs/page'}, state:{type:'array',maxItems:40,items:{$ref:'#/$defs/state'}}, dataSources:{type:'array',maxItems:10,items:{$ref:'#/$defs/dataSource'}}, regions:{type:'array',minItems:1,maxItems:20,items:{$ref:'#/$defs/region'}}}, $defs:{ ident:{type:'string',pattern:'^[a-z][a-z0-9-]{1,62}$'}, page:{type:'object',additionalProperties:false,required:['name','route','title','type','layout'],properties:{name:{type:'string',minLength:2,maxLength:80},route:{type:'string',pattern:'^/[a-z0-9][a-z0-9/-]{0,80}$'},title:{type:'string',minLength:2,maxLength:100},type:{enum:['list-page','form-page','detail-page']},layout:{const:'standard'}}}, state:{type:'object',additionalProperties:false,required:['name','type','defaultValue'],properties:{name:{$ref:'#/$defs/ident'},type:{enum:['string','number','boolean','object','array']},defaultValue:{}}}, dataSource:{type:'object',additionalProperties:false,required:['id','type','model','data'],properties:{id:{$ref:'#/$defs/ident'},type:{const:'mock'},model:{type:'string',pattern:'^[A-Z][A-Za-z0-9]{1,60}$'},data:{type:'array',maxItems:50,items:{type:'object'}}}}, action:{oneOf:[{type:'object',additionalProperties:false,required:['type','target'],properties:{type:{const:'navigate'},target:{type:'string',pattern:'^/[a-z0-9][a-z0-9/-]{0,80}$'}}},{type:'object',additionalProperties:false,required:['type','state','value'],properties:{type:{const:'set-state'},state:{$ref:'#/$defs/ident'},value:{}}},{type:'object',additionalProperties:false,required:['type','form'],properties:{type:{const:'reset-form'},form:{$ref:'#/$defs/ident'}}},{type:'object',additionalProperties:false,required:['type','form'],properties:{type:{const:'submit-mock'},form:{$ref:'#/$defs/ident'}}},{type:'object',additionalProperties:false,required:['type','dialog'],properties:{type:{const:'open-dialog'},dialog:{$ref:'#/$defs/ident'}}}]}, component:{type:'object',additionalProperties:false,required:['id','componentId','props'],properties:{id:{$ref:'#/$defs/ident'},componentId:{$ref:'#/$defs/ident'},props:{type:'object',additionalProperties:{}},bindings:{type:'object',additionalProperties:{$ref:'#/$defs/ident'}},events:{type:'object',additionalProperties:{$ref:'#/$defs/action'}},children:{type:'array',maxItems:20,items:{$ref:'#/$defs/component'}},dataSource:{$ref:'#/$defs/ident'},condition:{enum:['loading','empty','error','loaded']}}}, region:{type:'object',additionalProperties:false,required:['id','type','components'],properties:{id:{$ref:'#/$defs/ident'},type:{enum:['header','actions','search','filters','content','pagination','loading','empty','error','sections','cards']},components:{type:'array',maxItems:30,items:{$ref:'#/$defs/component'}}}} }} as const;
const ajv=new Ajv2020({allErrors:true,strict:false}); addFormats(ajv); const validateFn=ajv.compile(screenDslSchema);
export function validateScreenDsl(input: unknown): {valid:true; data:ScreenDsl}|{valid:false; issues:ValidationIssue[]} { const valid=validateFn(input); if(valid) return {valid:true,data:input as ScreenDsl}; return {valid:false,issues:(validateFn.errors??[]).map(e=>({code:'SCHEMA_VALIDATION',path:e.instancePath||'/',message:e.message??'Invalid DSL',severity:'error'}))}; }
export function normalizeScreenDsl(dsl: ScreenDsl): ScreenDsl { const regionOrder:RegionType[]=['header','actions','search','filters','content','sections','cards','pagination','loading','empty','error']; const norm={...dsl,page:{...dsl.page,name:dsl.page.name.trim(),route:'/'+slugify(dsl.page.route)},state:[...dsl.state].sort((a,b)=>a.name.localeCompare(b.name)),dataSources:[...dsl.dataSources].sort((a,b)=>a.id.localeCompare(b.id)),regions:[...dsl.regions].sort((a,b)=>regionOrder.indexOf(a.type)-regionOrder.indexOf(b.type)).map(r=>({...r,components:r.components.map(normalizeNode)}))}; return norm; }
function normalizeNode(n:ComponentNode):ComponentNode{ const props=Object.fromEntries(Object.entries(n.props).sort(([a],[b])=>a.localeCompare(b))); return {...n,props,children:n.children?.map(normalizeNode)}; }
