import { mkdir, readFile, writeFile, cp } from 'node:fs/promises';
import path from 'node:path';
import ts from 'typescript';
import { AngularPageGenerationModel } from '@dsl/angular-generation-model';
import { ComponentNode } from '@dsl/screen-dsl';
export interface GeneratedFile { path:string; content:string; }
export interface GenerationContext { imports:Set<string>; }
export interface ComponentRenderer<TNode extends ComponentNode=ComponentNode>{ componentId:string; collectDependencies(node:TNode,context:GenerationContext):void; render(node:TNode,context:GenerationContext):string; }
const esc=(v:unknown)=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
class SimpleRenderer implements ComponentRenderer{constructor(readonly componentId:string){} collectDependencies(_:ComponentNode,ctx:GenerationContext){ctx.imports.add(symbol(this.componentId));} render(n:ComponentNode,ctx:GenerationContext):string{this.collectDependencies(n,ctx); const p=n.props; const kids=(n.children??[]).map(c=>renderNode(c,ctx)).join('\n'); switch(n.componentId){case 'ds-page-header':return `<ds-page-header title="${esc(p.title)}" description="${esc(p.description??'')}">${kids}</ds-page-header>`;case 'ds-button':return `<ds-button label="${esc(p.label)}" variant="${esc(p.variant??'primary')}" size="${esc(p.size??'md')}"></ds-button>`;case 'ds-search-input':return `<ds-search-input label="${esc(p.label??'Pesquisar')}" placeholder="${esc(p.placeholder??'')}"></ds-search-input>`;case 'ds-select':return `<ds-select label="${esc(p.label)}" [options]="statusOptions" value="${esc(p.value??'')}"></ds-select>`;case 'ds-table':return `<ds-table [columns]="contractColumns" [rows]="contracts"></ds-table>`;case 'ds-pagination':return `<ds-pagination [page]="page()" [pageSize]="${esc(p.pageSize??10)}" [total]="contracts.length"></ds-pagination>`;case 'ds-loading':return `<ds-loading label="${esc(p.label??'Carregando')}"></ds-loading>`;case 'ds-empty-state':return `<ds-empty-state title="${esc(p.title)}" description="${esc(p.description??'')}"></ds-empty-state>`;case 'ds-alert':return `<ds-alert title="${esc(p.title)}" message="${esc(p.message)}" tone="${esc(p.tone??'danger')}"></ds-alert>`;case 'ds-tag':return `<ds-tag label="${esc(p.label)}" tone="${esc(p.tone??'neutral')}"></ds-tag>`;default:return `<${n.componentId}></${n.componentId}>`;}}}
export const renderers=Object.fromEntries(['ds-page','ds-page-header','ds-button','ds-input','ds-search-input','ds-select','ds-textarea','ds-checkbox','ds-date-picker','ds-filter-bar','ds-table','ds-pagination','ds-card','ds-tag','ds-alert','ds-loading','ds-empty-state'].map(id=>[id,new SimpleRenderer(id)]));
function symbol(id:string){return id.split('-').map(x=>x==='ds'?'Ds':x[0]!.toUpperCase()+x.slice(1)).join('')+'Component';}
function renderNode(n:ComponentNode,ctx:GenerationContext):string{const r=renderers[n.componentId]; if(!r) throw new Error(`Renderer ausente ${n.componentId}`); return r.render(n,ctx);}
export function generateAngularFiles(model:AngularPageGenerationModel):GeneratedFile[]{ const ctx:{imports:Set<string>}={imports:new Set()}; const html=model.dsl.regions.map(r=>`<section class="region region-${r.type}">\n${r.components.map(c=>renderNode(c,ctx)).join('\n')}\n</section>`).join('\n'); const imports=[...ctx.imports].sort().join(', '); const tsContent=`import { ChangeDetectionStrategy, Component, signal } from '@angular/core';\nimport { ${imports} } from '../../design-system';\nimport { contractsMock } from './${model.fileName}.mock';\n\n@Component({ selector: '${model.selector}', standalone: true, imports: [${imports}], templateUrl: './${model.fileName}.page.html', styleUrl: './${model.fileName}.page.scss', changeDetection: ChangeDetectionStrategy.OnPush })\nexport class ${model.className} {\n  readonly loading = signal(false);\n  readonly empty = signal(false);\n  readonly error = signal(false);\n  readonly loaded = signal(true);\n  readonly page = signal(1);\n  readonly contracts = contractsMock;\n  readonly statusOptions = [{ label: 'Todos', value: '' }, { label: 'Ativo', value: 'Ativo' }, { label: 'Pendente', value: 'Pendente' }];\n  readonly contractColumns = [{ key: 'number', label: 'Número' }, { key: 'supplier', label: 'Fornecedor' }, { key: 'status', label: 'Status' }, { key: 'value', label: 'Valor' }];\n}\n`; const base=`src/app/pages/${model.fileName}`; return [{path:`${base}/${model.fileName}.page.ts`,content:tsContent},{path:`${base}/${model.fileName}.page.html`,content:html},{path:`${base}/${model.fileName}.page.scss`,content:'.region { margin-bottom: 1rem; }\n'},{path:`${base}/${model.fileName}.models.ts`,content:`export interface Contract { number: string; supplier: string; status: string; value: string; }\n`},{path:`${base}/${model.fileName}.mock.ts`,content:`import { Contract } from './${model.fileName}.models';\nexport const contractsMock: readonly Contract[] = ${JSON.stringify(model.mockData[0]?.data??[],null,2)};\n`},{path:`${base}/${model.fileName}.page.spec.ts`,content:`import { ${model.className} } from './${model.fileName}.page';\ndescribe('${model.className}', () => { it('exposes mocked contracts', () => { const page = new ${model.className}(); expect(page.contracts.length).toBeGreaterThan(0); }); });\n`}];}
export async function writeAngularProject(templateDir:string,outDir:string,model:AngularPageGenerationModel):Promise<GeneratedFile[]>{ await mkdir(outDir,{recursive:true}); await cp(templateDir,outDir,{recursive:true}); const files=generateAngularFiles(model); for(const f of files){ const target=path.join(outDir,f.path); await mkdir(path.dirname(target),{recursive:true}); await writeFile(target,f.content);} await registerRoute(path.join(outDir,'src/app/app.routes.ts'),model); return files; }
export async function registerRoute(routesFile:string,model:AngularPageGenerationModel):Promise<void>{ const current=await readFile(routesFile,'utf8'); if(current.includes(`path: '${model.route}'`)) return; ts.createSourceFile(routesFile,current,ts.ScriptTarget.Latest,true); const entry=`  {\n    path: '${model.route}',\n    loadComponent: () => import('./pages/${model.fileName}/${model.fileName}.page').then((module) => module.${model.className}),\n  },\n`; const updated=current.replace(/export const routes: Routes = \[/,`export const routes: Routes = [\n${entry}`); await writeFile(routesFile,updated); }
